# Setup
title:        The Morgan And Grand Iron Clojure Compiler
shorttitle:   The MAGIC Compiler
tagline:      A high-performance Clojure compiler library targeting the Common Language Runtime
baseurl:      "http://nas.sr/magic"
future: true

repo_url: https://github.com/nasser/magic

# paginate:     5

# About/contact
author:
  name:       Ramsey Nasser
  url:        http://nas.sr

# Gems
plugins:
  - jekyll-mermaid
  - jekyll-paginate

paginate: 2
paginate_path: "/:num/"

#Others
markdown: kramdown

mermaid:
  src: '/js/mermaid.js'
